<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="47690" started-at="2023-07-03T20:45:43 IST" finished-at="2023-07-03T20:46:31 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="47690" started-at="2023-07-03T20:45:43 IST" finished-at="2023-07-03T20:46:31 IST">
      <class name="com.TestLayer.Demo1">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.TestLayer.Demo1@7403c468]" name="setup" is-config="true" duration-ms="26046" started-at="2023-07-03T20:45:44 IST" finished-at="2023-07-03T20:46:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login()[pri:1, instance:com.TestLayer.Demo1@7403c468]" name="login" duration-ms="1955" started-at="2023-07-03T20:46:10 IST" finished-at="2023-07-03T20:46:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="validateTitle()[pri:2, instance:com.TestLayer.Demo1@7403c468]" name="validateTitle" duration-ms="6610" started-at="2023-07-03T20:46:15 IST" finished-at="2023-07-03T20:46:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method status="FAIL" signature="validateUrl()[pri:3, instance:com.TestLayer.Demo1@7403c468]" name="validateUrl" duration-ms="12" started-at="2023-07-03T20:46:23 IST" finished-at="2023-07-03T20:46:23 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.TestLayer.Demo1.validateUrl(Demo1.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUrl -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.TestLayer.Demo1@7403c468]" name="teardown" is-config="true" duration-ms="7845" started-at="2023-07-03T20:46:23 IST" finished-at="2023-07-03T20:46:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.TestLayer.Demo1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
